apiVersion: apps/v1
kind: Deployment
metadata:
  name: voucher-management-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voucher-management-web
  template:
    metadata:
      labels:
        app: voucher-management-web
    spec:
      containers:
        - name: voucher-management-web
          image: public.ecr.aws/s6y5a7e8/voucher-web:VERSION
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: reactjs-k8s-service
spec:
  selector:
    app: voucher-management-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
