apiVersion: apps/v1
kind: Deployment
metadata:
  name: voucher-management-app
  namespace: voucher-management-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: voucher-management-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: voucher-management-app
    spec:
      containers:
        - name: voucher-management-app
          image: public.ecr.aws/s6y5a7e8/voucher-app:v10
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: db_password
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: aws_s3_access_key_id 
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: aws_s3_secret_key_id
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: SPRING_PROFILES_ACTIVE
          resources:
           requests:
             cpu: "200m"
             memory: "256Mi"
           limits:
             cpu: "500m"
             memory: "512Mi"
